package tools.predicatesExpressions.expressionEvaluator.sourceEvaluer;

import tools.predicatesExpressions.expressionEvaluator.AbstractEvaluator;

public interface AndExpressionSegment extends ShortCircuitExpressionSegment, AbstractEvaluator {
}