package tools.predicatesExpressions.expressionEvaluator.sourceEvaluer;

import tools.predicatesExpressions.expressionEvaluator.AbstractEvaluator;

public interface OrExpressionSegment extends ShortCircuitExpressionSegment, AbstractEvaluator {
}